package com.samples.sort;

/**
 * Bucket sort assumes that the input is drawn from a uniform distribution and has an average-case running time of O(n).
 * bucket sort assumes that the input is generated by a random process that distributes elements uniformly and independently over the interval [0,1).
 * Bucket sort divides the interval [0,1) into n equal-sized subintervals, or buckets, and then distributes the n input numbers into the buckets.
 * To produce the output, we simply sort the numbers in each bucket and then go through the buckets in order, listing the elements in each.
 * 
 *
 */
public class BucketSort {

}
